pollers:
  log-level: debug
  expiry-checker:
    interval: 5s
    timeout: 10s
  btc-subscriber:
    interval: 5s
    timeout: 10s
db:
  username: root
  password: example
  address: "mongodb://localhost:27017"
  db-name: staking-api-service
btc:
  endpoint: localhost:18332
  disable-tls: false
  net-params: testnet
  rpc-user: rpcuser
  rpc-pass: rpcpass
metrics:
  host: 0.0.0.0
  port: 2112