name: ci

on:
  pull_request:
    branches:
    - '**'

jobs:
  lint_test:
    uses: babylonlabs-io/.github/.github/workflows/reusable_go_lint_test.yml@cfbd5e4db5e575edf77a160fe533918c4f3a4498  # v0.13.2
    with:
      go-version: '1.24.3'
      go-lint-version: 'v1.64.8'
      run-unit-tests: true
      run-integration-tests: false
      run-lint: true
      run-build: true
      run-gosec: true
      gosec-args: "-no-fail ./..."

  docker_pipeline:
    permissions:
      contents: read
      id-token: write
      security-events: write
    uses: babylonlabs-io/.github/.github/workflows/reusable_docker_pipeline.yml@0adff9d36a387ebfc921621f2e6b357230f8c08e # v0.18.1
    secrets: inherit
    with:
      publish: false
      dockerfile: ./contrib/images/staking-expiry-checker/Dockerfile
